In [10]:
import numpy as np
import rir_generator as rir
import pandas as pd
import torch
import tqdm

from utils.model import Geometry_estimator

In [ ]:
0    8.30
1    5.00
2    4.80
3    0.24
4    1.00
5    0.66
6    0.78
7    0.38
8    0.48

In [36]:
h = rir.generate(
    c=340,                                      # Sound velocity (m/s)
    fs=8000,                                    # Sample frequency (samples/s)
    r=np.sort([4.20, 2.50, 2.40]),               # Receiver position(s) [x y z] (m)
    s=np.sort([2.40, 1.30, 1.40]),                 # Source position [x y z] (m)
    L=[8.30, 5.00, 4.80],                        # Room dimensions [x y z] (m)
    nsample=4096,                               # Number of output samples
    beta=np.sort([0.24, 1.00, 0.66, 0.78, 0.38, 0.48])                    # Room reflection coefficients [x1 x2 y1 y2 z1 z2]
)
h

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       ...,
       [-1.01968700e-07],
       [ 8.04393176e-10],
       [-6.33972618e-08]])

In [108]:
np.isnan(h).any() == True

False

In [22]:
room_geo  = np.array([np.random.randint(low=60, high=100)/10, np.random.randint(low=50, high=80)/10, np.random.randint(low=40, high=60)/10])
# random room coeffs
room_coeff = np.random.uniform(size=(6))
# random source and receiver position
source_position = [np.random.randint(low=(len*10)/2-10, high=(len*10)/2+10)/10 for len in room_geo]
receiver_position = [np.random.randint(low=(len*10)/2-10, high=(len*10)/2+10)/10 for len in room_geo]
#
#print("Room geometry: ", room_geo, " receiver position: ", receiver_position, "source position: ", source_position, "room coeff: ", room_coeff)
# generate ISM data
h = rir.generate(
    c=340,                                      # Sound velocity (m/s)
    fs=8000,                                    # Sample frequency (samples/s)
    r=np.sort(receiver_position),               # Receiver position(s) [x y z] (m)
    s=np.sort(source_position),                 # Source position [x y z] (m)
    L=np.sort(room_geo),                        # Room dimensions [x y z] (m)
    nsample=4096,                               # Number of output samples
    beta=np.sort(room_coeff)                    # Room reflection coefficients [x1 x2 y1 y2 z1 z2]
)

# concat the geometry and reflection coefficients
h = np.concatenate((h.squeeze(), np.concatenate((room_geo, room_coeff))))
h = np.expand_dims(h, axis=1)
# save ISM data
print("ISM data: ", h.shape)

ISM data:  (4105, 1)


In [54]:
np.random.uniform(size=(6))

array([0.94823008, 0.55364852, 0.25966412, 0.98941496, 0.08847435,
       0.53749568])

In [51]:
np.isin(1.000, np.array([1, 2,3,4]))

array(True)

In [58]:
round(0.99578914, 2)

1.0

In [61]:
'%.2f'%(0.99578914)

'1.00'

In [250]:
np.random.seed(14)
print("pie", np.random.randint(low=1,high = 9))
count = 0
count2 = 0
for i in tqdm.trange(10000):
    room_geo  = [np.random.randint(low=60, high=100)/10, np.random.randint(low=50, high=80)/10, np.random.randint(low=40, high=60)/10]
  
    source_position = [np.random.randint(low=(len*10)/2-20, high=(len*10)/2+20)/10 for len in room_geo]
    receiver_position = []
    while True:
        receiver_position = [np.random.randint(low=(len*10)/2-20, high=(len*10)/2+20)/10 for len in room_geo]
        if (np.sort(source_position) == np.sort(receiver_position)).all():
            count += 1
            print(i, " receiver position: ", receiver_position, "source position: ", source_position)
            continue
        else:
            count2 += 1
            break

        #receiver_position = [np.random.randint(low=(len*10)/2-20, high=(len*10)/2+20)/10 for len in room_geo]
    #print(i,"Room geometry: ", room_geo, " receiver position: ", receiver_position, "source position: ", source_position, "room coeff: ", room_coeff)
print("count: ",count, count2)

pie 4


100%|██████████| 10000/10000 [00:00<00:00, 36120.24it/s]

9114  receiver position:  [4.9, 3.7, 2.9] source position:  [4.9, 3.7, 2.9]
count:  1 10000


In [202]:
s = np.array([2.8, 3.3, 1.9])   # org
r = np.array([1.9, 2.8, 3.3])   # same but scattered  
q = np.array([1.7, 2.8, 3.2])   # 1 ele same
t = np.array([1.7, 2.8, 3.3])   # 2 ele same

In [199]:
(np.sort(s) == np.sort(t))

array([False,  True,  True])

In [200]:
(np.sort(s) == np.sort(t)).all()

False

In [201]:
np.all(np.sort(s), np.sort(t))

TypeError: only integer scalar arrays can be converted to a scalar index

In [126]:
np.random.seed(0)
print(np.random.uniform(size=(6)))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]


In [110]:
for i in tqdm.trange(10000):
    x = np.random.uniform(size=(6)).round(2)
    x[x==1.0] = 0.99
    y = x.copy()
    y[y==1.0] = 0.99
    if np.isin(1.0, x):
        print(i, x, y)

100%|██████████| 10000/10000 [00:00<00:00, 40526.67it/s]


In [3]:
torch.jit.script(Geometry_estimator())

RecursiveScriptModule(
  original_name=Geometry_estimator
  (convLayers): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(
      original_name=Conv_block
      (seq): RecursiveScriptModule(
        original_name=Sequential
        (0): RecursiveScriptModule(original_name=Conv1d)
        (1): RecursiveScriptModule(original_name=BatchNorm1d)
        (2): RecursiveScriptModule(original_name=ReLU)
      )
    )
    (1): RecursiveScriptModule(
      original_name=Conv_block
      (seq): RecursiveScriptModule(
        original_name=Sequential
        (0): RecursiveScriptModule(original_name=Conv1d)
        (1): RecursiveScriptModule(original_name=BatchNorm1d)
        (2): RecursiveScriptModule(original_name=ReLU)
      )
    )
    (2): RecursiveScriptModule(
      original_name=Conv_block
      (seq): RecursiveScriptModule(
        original_name=Sequential
        (0): RecursiveScriptModule(original_name=Conv1d)
        (1): RecursiveScriptModule(original_n

In [2]:
gg = torch.compile(Geometry_estimator())
gg

OptimizedModule(
  (_orig_mod): Geometry_estimator(
    (convLayers): Sequential(
      (0): Conv_block(
        (seq): Sequential(
          (0): Conv1d(1, 32, kernel_size=(4,), stride=(4,), bias=False)
          (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
      )
      (1): Conv_block(
        (seq): Sequential(
          (0): Conv1d(32, 32, kernel_size=(2,), stride=(2,), bias=False)
          (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
      )
      (2): Conv_block(
        (seq): Sequential(
          (0): Conv1d(32, 128, kernel_size=(8,), stride=(8,), bias=False)
          (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
      )
      (3): Conv_block(
        (seq): Sequential(
          (0): Conv1d(128, 128, kernel_size=(2,), stride=(2,), bias=False)
          (1): Bat

In [12]:
room_geo

array([7.3, 5.1, 5.1])

In [23]:
dd = np.load("./rirData/ism_10k.npy")

In [21]:
dd = np.concatenate((dd[:2450,:] , dd[2452:,:]))

In [22]:
dd.shape

(9998, 4105)

In [24]:
data = pd.DataFrame(dd[2450:2452])
#tuples = []
#data.iloc[1][:9]

In [31]:
data.shape

(2, 4105)

In [34]:
data.iloc[0][:9]

0    8.30
1    5.00
2    4.80
3    0.24
4    1.00
5    0.66
6    0.78
7    0.38
8    0.48
Name: 0, dtype: float64

In [11]:
data = torch.tensor(data)


ValueError: expected sequence of length 100 at dim 0 (got 4105)

In [5]:
from utils.dataLoader import ISMDataset as ism

batches = torch.utils.data.DataLoader(ism(data=data), batch_size=5, shuffle=True, num_workers=4)

In [15]:
len(batches)

20

In [11]:
a,s=0, 0
for idx,b in enumerate(tqdm(batches)):
    
    print(idx,"A",a,"S", s,"C")

TypeError: 'module' object is not callable

In [19]:
for xc,data in tqdm.tqdm(enumerate(batches, 0), unit="batch", total=len(batches)):
    #print(xc)
    x=xc

100%|██████████| 20/20 [00:00<00:00, 51.97batch/s]


In [18]:
for batch_index, data in tqdm.tqdm(enumerate(batches), unit='batch',
                              total=len(batches),
                              desc ="My Progress Bar"):
    print(batch_index)

My Progress Bar:  40%|████      | 8/20 [00:00<00:00, 32.04batch/s]

0
1
2
3
4
5
6
7
8


My Progress Bar: 100%|██████████| 20/20 [00:00<00:00, 53.10batch/s]

9
10
11
12
13
14
15
16
17
18
19


In [31]:
a = a.cuda()

In [37]:
torch.randn((2,5,1)).reshape(2, -1).size()

torch.Size([2, 5])

In [33]:
a

tensor([[9.9000, 7.3000, 4.7000],
        [7.3000, 5.3000, 5.7000],
        [6.6000, 7.2000, 5.8000],
        [6.6000, 7.1000, 5.1000],
        [7.9000, 7.2000, 4.6000]], device='cuda:0', dtype=torch.float64)

In [11]:
tuples.append(data[:3])
tuples.append(data[3:9])
tuples.append(data[9:])

In [12]:
tuples[0]


0     1     2     3     4     5     6     7     8         9     ...  \
0   6.6   7.1   5.1  0.74  0.40  0.06  0.98  0.67  0.94 -0.000003  ...   
1   7.8   6.1   4.0  0.85  0.75  0.45  0.51  0.28  0.72  0.000123  ...   
2   7.3   5.3   5.7  0.03  0.56  0.75  0.01  0.87  0.47 -0.000358  ...   

           4095          4096          4097          4098          4099  \
0 -7.382923e-06 -8.597558e-06 -6.104812e-06 -6.436633e-06 -5.621640e-06   
1 -6.295699e-08 -1.326515e-07 -6.025048e-07 -3.875286e-07 -3.076428e-07   
2 -4.996883e-10 -9.963400e-10  2.173851e-10 -1.465849e-09  3.027487e-09   

           4100          4101          4102          4103          4104  
0 -1.587070e-06 -8.767135e-06  9.240165e-06  1.006314e-05 -6.056572e-06  
1 -3.986695e-07 -3.510979e-07 -2.832408e-07 -2.644297e-07 -2.569008e-07  
2  1.665801e-08  1.181978e-08  3.101104e-09 -6.473393e-09  1.209245e-08  

[3 rows x 4105 columns]